using System.Collections.Frozen;

namespace CarTelemetry.Core.Obd;

/// <summary>
/// Resolves OBD-II code families and common diagnostic descriptions.
/// </summary>
public interface IDtcDescriptionService
{
    string? GetDescription(string dtcCode);
    string GetSystemName(string systemCode);
}

public sealed class DtcDescriptionService : IDtcDescriptionService
{
    private static readonly FrozenDictionary<string, string> SystemNames = new Dictionary<string, string>
    {
        ["P"] = "Powertrain",
        ["C"] = "Chassis", 
        ["B"] = "Body",
        ["U"] = "Network/Communication"
    }.ToFrozenDictionary();

    private static readonly FrozenDictionary<string, string> DtcDescriptions = new Dictionary<string, string>
    {
        ["P0001"] = "Fuel Volume Regulator Control Circuit/Open",
        ["P0002"] = "Fuel Volume Regulator Control Circuit Range/Performance",
        ["P0003"] = "Fuel Volume Regulator Control Circuit Low",
        ["P0004"] = "Fuel Volume Regulator Control Circuit High",
        ["P0005"] = "Fuel Shutoff Valve A Control Circuit/Open",
        ["P0006"] = "Fuel Shutoff Valve A Control Circuit Low",
        ["P0007"] = "Fuel Shutoff Valve A Control Circuit High",
        ["P0008"] = "Engine Position System Performance Bank 1",
        ["P0009"] = "Engine Position System Performance Bank 2",
        ["P0010"] = "Intake Camshaft Position Actuator Circuit/Open (Bank 1)",
        
        ["P0100"] = "Mass or Volume Air Flow Circuit Malfunction",
        ["P0101"] = "Mass or Volume Air Flow Circuit Range/Performance Problem",
        ["P0102"] = "Mass or Volume Air Flow Circuit Low Input",
        ["P0103"] = "Mass or Volume Air Flow Circuit High Input",
        ["P0104"] = "Mass or Volume Air Flow Circuit Intermittent",
        ["P0105"] = "Manifold Absolute Pressure/Barometric Pressure Circuit Malfunction",
        ["P0106"] = "Manifold Absolute Pressure/Barometric Pressure Circuit Range/Performance Problem",
        ["P0107"] = "Manifold Absolute Pressure/Barometric Pressure Circuit Low Input",
        ["P0108"] = "Manifold Absolute Pressure/Barometric Pressure Circuit High Input",
        ["P0109"] = "Manifold Absolute Pressure/Barometric Pressure Circuit Intermittent",
        ["P0110"] = "Intake Air Temperature Circuit Malfunction",
        ["P0111"] = "Intake Air Temperature Circuit Range/Performance Problem",
        ["P0112"] = "Intake Air Temperature Circuit Low Input",
        ["P0113"] = "Intake Air Temperature Circuit High Input",
        ["P0114"] = "Intake Air Temperature Circuit Intermittent",
        ["P0115"] = "Engine Coolant Temperature Circuit Malfunction",
        ["P0116"] = "Engine Coolant Temperature Circuit Range/Performance Problem",
        ["P0117"] = "Engine Coolant Temperature Circuit Low Input",
        ["P0118"] = "Engine Coolant Temperature Circuit High Input",
        ["P0119"] = "Engine Coolant Temperature Circuit Intermittent",
        ["P0120"] = "Throttle/Pedal Position Sensor/Switch A Circuit Malfunction",
        ["P0121"] = "Throttle/Pedal Position Sensor/Switch A Circuit Range/Performance Problem",
        ["P0122"] = "Throttle/Pedal Position Sensor/Switch A Circuit Low Input",
        ["P0123"] = "Throttle/Pedal Position Sensor/Switch A Circuit High Input",
        ["P0124"] = "Throttle/Pedal Position Sensor/Switch A Circuit Intermittent",
        ["P0125"] = "Insufficient Coolant Temperature for Closed Loop Fuel Control",
        ["P0126"] = "Insufficient Coolant Temperature for Stable Operation",
        ["P0127"] = "Intake Air Temperature Too High",
        ["P0128"] = "Coolant Thermostat (Coolant Temperature Below Thermostat Regulating Temperature)",
        ["P0129"] = "Barometric Pressure Too Low",
        ["P0130"] = "O2 Sensor Circuit Malfunction (Bank 1, Sensor 1)",
        ["P0131"] = "O2 Sensor Circuit Low Voltage (Bank 1, Sensor 1)",
        ["P0132"] = "O2 Sensor Circuit High Voltage (Bank 1, Sensor 1)",
        ["P0133"] = "O2 Sensor Circuit Slow Response (Bank 1, Sensor 1)",
        ["P0134"] = "O2 Sensor Circuit No Activity Detected (Bank 1, Sensor 1)",
        ["P0135"] = "O2 Sensor Heater Circuit Malfunction (Bank 1, Sensor 1)",
        ["P0136"] = "O2 Sensor Circuit Malfunction (Bank 1, Sensor 2)",
        ["P0137"] = "O2 Sensor Circuit Low Voltage (Bank 1, Sensor 2)",
        ["P0138"] = "O2 Sensor Circuit High Voltage (Bank 1, Sensor 2)",
        ["P0139"] = "O2 Sensor Circuit Slow Response (Bank 1, Sensor 2)",
        ["P0140"] = "O2 Sensor Circuit No Activity Detected (Bank 1, Sensor 2)",
        ["P0141"] = "O2 Sensor Heater Circuit Malfunction (Bank 1, Sensor 2)",
        ["P0142"] = "O2 Sensor Circuit Malfunction (Bank 1, Sensor 3)",
        ["P0143"] = "O2 Sensor Circuit Low Voltage (Bank 1, Sensor 3)",
        ["P0144"] = "O2 Sensor Circuit High Voltage (Bank 1, Sensor 3)",
        ["P0145"] = "O2 Sensor Circuit Slow Response (Bank 1, Sensor 3)",
        ["P0146"] = "O2 Sensor Circuit No Activity Detected (Bank 1, Sensor 3)",
        ["P0147"] = "O2 Sensor Heater Circuit Malfunction (Bank 1, Sensor 3)",
        ["P0148"] = "Fuel Delivery Error",
        ["P0149"] = "Fuel Timing Error",
        ["P0150"] = "O2 Sensor Circuit Malfunction (Bank 2, Sensor 1)",
        ["P0151"] = "O2 Sensor Circuit Low Voltage (Bank 2, Sensor 1)",
        ["P0152"] = "O2 Sensor Circuit High Voltage (Bank 2, Sensor 1)",
        ["P0153"] = "O2 Sensor Circuit Slow Response (Bank 2, Sensor 1)",
        ["P0154"] = "O2 Sensor Circuit No Activity Detected (Bank 2, Sensor 1)",
        ["P0155"] = "O2 Sensor Heater Circuit Malfunction (Bank 2, Sensor 1)",
        ["P0156"] = "O2 Sensor Circuit Malfunction (Bank 2, Sensor 2)",
        ["P0157"] = "O2 Sensor Circuit Low Voltage (Bank 2, Sensor 2)",
        ["P0158"] = "O2 Sensor Circuit High Voltage (Bank 2, Sensor 2)",
        ["P0159"] = "O2 Sensor Circuit Slow Response (Bank 2, Sensor 2)",
        ["P0160"] = "O2 Sensor Circuit No Activity Detected (Bank 2, Sensor 2)",
        ["P0161"] = "O2 Sensor Heater Circuit Malfunction (Bank 2, Sensor 2)",
        ["P0162"] = "O2 Sensor Circuit Malfunction (Bank 2, Sensor 3)",
        ["P0163"] = "O2 Sensor Circuit Low Voltage (Bank 2, Sensor 3)",
        ["P0164"] = "O2 Sensor Circuit High Voltage (Bank 2, Sensor 3)",
        ["P0165"] = "O2 Sensor Circuit Slow Response (Bank 2, Sensor 3)",
        ["P0166"] = "O2 Sensor Circuit No Activity Detected (Bank 2, Sensor 3)",
        ["P0167"] = "O2 Sensor Heater Circuit Malfunction (Bank 2, Sensor 3)",
        ["P0168"] = "Fuel Temperature Too High",
        ["P0169"] = "Incorrect Fuel Composition",
        ["P0170"] = "Fuel Trim Malfunction (Bank 1)",
        ["P0171"] = "System Too Lean (Bank 1)",
        ["P0172"] = "System Too Rich (Bank 1)",
        ["P0173"] = "Fuel Trim Malfunction (Bank 2)",
        ["P0174"] = "System Too Lean (Bank 2)",
        ["P0175"] = "System Too Rich (Bank 2)",
        ["P0176"] = "Fuel Composition Sensor Circuit Malfunction",
        ["P0177"] = "Fuel Composition Sensor Circuit Range/Performance",
        ["P0178"] = "Fuel Composition Sensor Circuit Low Input",
        ["P0179"] = "Fuel Composition Sensor Circuit High Input",
        ["P0180"] = "Fuel Temperature Sensor A Circuit Malfunction",
        
        ["P0200"] = "Injector Circuit Malfunction",
        ["P0201"] = "Injector Circuit Malfunction - Cylinder 1",
        ["P0202"] = "Injector Circuit Malfunction - Cylinder 2",
        ["P0203"] = "Injector Circuit Malfunction - Cylinder 3",
        ["P0204"] = "Injector Circuit Malfunction - Cylinder 4",
        ["P0205"] = "Injector Circuit Malfunction - Cylinder 5",
        ["P0206"] = "Injector Circuit Malfunction - Cylinder 6",
        ["P0207"] = "Injector Circuit Malfunction - Cylinder 7",
        ["P0208"] = "Injector Circuit Malfunction - Cylinder 8",
        ["P0209"] = "Injector Circuit Malfunction - Cylinder 9",
        ["P0210"] = "Injector Circuit Malfunction - Cylinder 10",
        ["P0211"] = "Injector Circuit Malfunction - Cylinder 11",
        ["P0212"] = "Injector Circuit Malfunction - Cylinder 12",
        ["P0213"] = "Cold Start Injector 1 Malfunction",
        ["P0214"] = "Cold Start Injector 2 Malfunction",
        ["P0215"] = "Engine Shutoff Solenoid Malfunction",
        ["P0216"] = "Injection Timing Control Circuit Malfunction",
        ["P0217"] = "Engine Over Temperature Condition",
        ["P0218"] = "Transmission Over Temperature Condition",
        ["P0219"] = "Engine Over Speed Condition",
        ["P0220"] = "Throttle/Pedal Position Sensor/Switch B Circuit Malfunction",
        ["P0221"] = "Throttle/Pedal Position Sensor/Switch B Circuit Range/Performance Problem",
        ["P0222"] = "Throttle/Pedal Position Sensor/Switch B Circuit Low Input",
        ["P0223"] = "Throttle/Pedal Position Sensor/Switch B Circuit High Input",
        ["P0224"] = "Throttle/Pedal Position Sensor/Switch B Circuit Intermittent",
        ["P0225"] = "Throttle/Pedal Position Sensor/Switch C Circuit Malfunction",
        ["P0226"] = "Throttle/Pedal Position Sensor/Switch C Circuit Range/Performance Problem",
        ["P0227"] = "Throttle/Pedal Position Sensor/Switch C Circuit Low Input",
        ["P0228"] = "Throttle/Pedal Position Sensor/Switch C Circuit High Input",
        ["P0229"] = "Throttle/Pedal Position Sensor/Switch C Circuit Intermittent",
        ["P0230"] = "Fuel Pump Primary Circuit Malfunction",
        ["P0231"] = "Fuel Pump Secondary Circuit Low",
        ["P0232"] = "Fuel Pump Secondary Circuit High",
        ["P0233"] = "Fuel Pump Secondary Circuit Intermittent",
        ["P0234"] = "Engine Over Boost Condition",
        ["P0235"] = "Turbocharger Boost Sensor A Circuit Malfunction",
        ["P0236"] = "Turbocharger Boost Sensor A Circuit Range/Performance",
        ["P0237"] = "Turbocharger Boost Sensor A Circuit Low",
        ["P0238"] = "Turbocharger Boost Sensor A Circuit High",
        ["P0239"] = "Turbocharger Boost Sensor B Circuit Malfunction",
        ["P0240"] = "Turbocharger Boost Sensor B Circuit Range/Performance",
        ["P0241"] = "Turbocharger Boost Sensor B Circuit Low",
        ["P0242"] = "Turbocharger Boost Sensor B Circuit High",
        ["P0243"] = "Turbocharger Wastegate Solenoid A Malfunction",
        ["P0244"] = "Turbocharger Wastegate Solenoid A Range/Performance",
        ["P0245"] = "Turbocharger Wastegate Solenoid A Low",
        ["P0246"] = "Turbocharger Wastegate Solenoid A High",
        ["P0247"] = "Turbocharger Wastegate Solenoid B Malfunction",
        ["P0248"] = "Turbocharger Wastegate Solenoid B Range/Performance",
        ["P0249"] = "Turbocharger Wastegate Solenoid B Low",
        ["P0250"] = "Turbocharger Wastegate Solenoid B High",
        
        ["P0300"] = "Random/Multiple Cylinder Misfire Detected",
        ["P0301"] = "Cylinder 1 Misfire Detected",
        ["P0302"] = "Cylinder 2 Misfire Detected", 
        ["P0303"] = "Cylinder 3 Misfire Detected",
        ["P0304"] = "Cylinder 4 Misfire Detected",
        ["P0305"] = "Cylinder 5 Misfire Detected",
        ["P0306"] = "Cylinder 6 Misfire Detected",
        ["P0307"] = "Cylinder 7 Misfire Detected",
        ["P0308"] = "Cylinder 8 Misfire Detected",
        ["P0309"] = "Cylinder 9 Misfire Detected",
        ["P0310"] = "Cylinder 10 Misfire Detected",
        ["P0311"] = "Cylinder 11 Misfire Detected",
        ["P0312"] = "Cylinder 12 Misfire Detected",
        ["P0313"] = "Misfire Detected with Low Fuel",
        ["P0314"] = "Single Cylinder Misfire (Cylinder Not Specified)",
        ["P0315"] = "Crankshaft Position System Variation Not Learned",
        ["P0316"] = "Misfire Detected on Startup (First 1000 Revolutions)",
        ["P0317"] = "Rough Road Hardware Not Present",
        ["P0318"] = "Rough Road Sensor Signal Malfunction",
        ["P0319"] = "Rough Road Sensor Signal Malfunction",
        ["P0320"] = "Ignition/Distributor Engine Speed Input Circuit Malfunction",
        ["P0321"] = "Ignition/Distributor Engine Speed Input Circuit Range/Performance",
        ["P0322"] = "Ignition/Distributor Engine Speed Input Circuit No Signal",
        ["P0323"] = "Ignition/Distributor Engine Speed Input Circuit Intermittent",
        ["P0324"] = "Knock Control System Error",
        ["P0325"] = "Knock Sensor 1 Circuit Malfunction (Bank 1 or Single Sensor)",
        ["P0326"] = "Knock Sensor 1 Circuit Range/Performance (Bank 1 or Single Sensor)",
        ["P0327"] = "Knock Sensor 1 Circuit Low Input (Bank 1 or Single Sensor)",
        ["P0328"] = "Knock Sensor 1 Circuit High Input (Bank 1 or Single Sensor)",
        ["P0329"] = "Knock Sensor 1 Circuit Input Intermittent (Bank 1 or Single Sensor)",
        ["P0330"] = "Knock Sensor 2 Circuit Malfunction (Bank 2)",
        ["P0331"] = "Knock Sensor 2 Circuit Range/Performance (Bank 2)",
        ["P0332"] = "Knock Sensor 2 Circuit Low Input (Bank 2)",
        ["P0333"] = "Knock Sensor 2 Circuit High Input (Bank 2)",
        ["P0334"] = "Knock Sensor 2 Circuit Input Intermittent (Bank 2)",
        ["P0335"] = "Crankshaft Position Sensor A Circuit Malfunction",
        ["P0336"] = "Crankshaft Position Sensor A Circuit Range/Performance",
        ["P0337"] = "Crankshaft Position Sensor A Circuit Low Input",
        ["P0338"] = "Crankshaft Position Sensor A Circuit High Input",
        ["P0339"] = "Crankshaft Position Sensor A Circuit Intermittent",
        ["P0340"] = "Camshaft Position Sensor Circuit Malfunction",
        ["P0341"] = "Camshaft Position Sensor Circuit Range/Performance",
        ["P0342"] = "Camshaft Position Sensor Circuit Low Input",
        ["P0343"] = "Camshaft Position Sensor Circuit High Input",
        ["P0344"] = "Camshaft Position Sensor Circuit Intermittent",
        ["P0345"] = "Camshaft Position Sensor A Circuit Malfunction (Bank 2)",
        ["P0346"] = "Camshaft Position Sensor A Circuit Range/Performance (Bank 2)",
        ["P0347"] = "Camshaft Position Sensor A Circuit Low Input (Bank 2)",
        ["P0348"] = "Camshaft Position Sensor A Circuit High Input (Bank 2)",
        ["P0349"] = "Camshaft Position Sensor A Circuit Intermittent (Bank 2)",
        ["P0350"] = "Ignition Coil Primary/Secondary Circuit Malfunction",
        ["P0351"] = "Ignition Coil A Primary/Secondary Circuit Malfunction",
        ["P0352"] = "Ignition Coil B Primary/Secondary Circuit Malfunction",
        ["P0353"] = "Ignition Coil C Primary/Secondary Circuit Malfunction",
        ["P0354"] = "Ignition Coil D Primary/Secondary Circuit Malfunction",
        ["P0355"] = "Ignition Coil E Primary/Secondary Circuit Malfunction",
        ["P0356"] = "Ignition Coil F Primary/Secondary Circuit Malfunction",
        ["P0357"] = "Ignition Coil G Primary/Secondary Circuit Malfunction",
        ["P0358"] = "Ignition Coil H Primary/Secondary Circuit Malfunction",
        ["P0359"] = "Ignition Coil I Primary/Secondary Circuit Malfunction",
        ["P0360"] = "Ignition Coil J Primary/Secondary Circuit Malfunction",
        ["P0361"] = "Ignition Coil K Primary/Secondary Circuit Malfunction",
        ["P0362"] = "Ignition Coil L Primary/Secondary Circuit Malfunction",
        
        ["P0400"] = "Exhaust Gas Recirculation Flow Malfunction",
        ["P0401"] = "Exhaust Gas Recirculation Flow Insufficient Detected",
        ["P0402"] = "Exhaust Gas Recirculation Flow Excessive Detected",
        ["P0403"] = "Exhaust Gas Recirculation Circuit Malfunction",
        ["P0404"] = "Exhaust Gas Recirculation Circuit Range/Performance",
        ["P0405"] = "Exhaust Gas Recirculation Sensor A Circuit Low",
        ["P0406"] = "Exhaust Gas Recirculation Sensor A Circuit High",
        ["P0407"] = "Exhaust Gas Recirculation Sensor B Circuit Low",
        ["P0408"] = "Exhaust Gas Recirculation Sensor B Circuit High",
        ["P0409"] = "Exhaust Gas Recirculation Sensor A Circuit Malfunction",
        ["P0410"] = "Secondary Air Injection System Malfunction",
        ["P0411"] = "Secondary Air Injection System Incorrect Flow Detected",
        ["P0412"] = "Secondary Air Injection System Switching Valve A Circuit Malfunction",
        ["P0413"] = "Secondary Air Injection System Switching Valve A Circuit Open",
        ["P0414"] = "Secondary Air Injection System Switching Valve A Circuit Shorted",
        ["P0415"] = "Secondary Air Injection System Switching Valve B Circuit Malfunction",
        ["P0416"] = "Secondary Air Injection System Switching Valve B Circuit Open",
        ["P0417"] = "Secondary Air Injection System Switching Valve B Circuit Shorted",
        ["P0418"] = "Secondary Air Injection System Relay A Circuit Malfunction",
        ["P0419"] = "Secondary Air Injection System Relay B Circuit Malfunction",
        ["P0420"] = "Catalyst System Efficiency Below Threshold (Bank 1)",
        ["P0421"] = "Warm Up Catalyst Efficiency Below Threshold (Bank 1)",
        ["P0422"] = "Main Catalyst Efficiency Below Threshold (Bank 1)",
        ["P0423"] = "Heated Catalyst Efficiency Below Threshold (Bank 1)",
        ["P0424"] = "Heated Catalyst Temperature Below Threshold (Bank 1)",
        ["P0425"] = "Catalyst Temperature Sensor 1 Circuit Malfunction (Bank 1)",
        ["P0426"] = "Catalyst Temperature Sensor 1 Circuit Range/Performance (Bank 1)",
        ["P0427"] = "Catalyst Temperature Sensor 1 Circuit Low Input (Bank 1)",
        ["P0428"] = "Catalyst Temperature Sensor 1 Circuit High Input (Bank 1)",
        ["P0429"] = "Catalyst Heater Control Circuit Malfunction (Bank 1)",
        ["P0430"] = "Catalyst System Efficiency Below Threshold (Bank 2)",
        ["P0431"] = "Warm Up Catalyst Efficiency Below Threshold (Bank 2)",
        ["P0432"] = "Main Catalyst Efficiency Below Threshold (Bank 2)",
        ["P0433"] = "Heated Catalyst Efficiency Below Threshold (Bank 2)",
        ["P0434"] = "Heated Catalyst Temperature Below Threshold (Bank 2)",
        ["P0435"] = "Catalyst Temperature Sensor 2 Circuit Malfunction (Bank 2)",
        ["P0436"] = "Catalyst Temperature Sensor 2 Circuit Range/Performance (Bank 2)",
        ["P0437"] = "Catalyst Temperature Sensor 2 Circuit Low Input (Bank 2)",
        ["P0438"] = "Catalyst Temperature Sensor 2 Circuit High Input (Bank 2)",
        ["P0439"] = "Catalyst Heater Control Circuit Malfunction (Bank 2)",
        ["P0440"] = "Evaporative Emission Control System Malfunction",
        ["P0441"] = "Evaporative Emission Control System Incorrect Purge Flow",
        ["P0442"] = "Evaporative Emission Control System Leak Detected (Small Leak)",
        ["P0443"] = "Evaporative Emission Control System Purge Control Valve Circuit Malfunction",
        ["P0444"] = "Evaporative Emission Control System Purge Control Valve Circuit Open",
        ["P0445"] = "Evaporative Emission Control System Purge Control Valve Circuit Shorted",
        ["P0446"] = "Evaporative Emission Control System Vent Control Circuit Malfunction",
        ["P0447"] = "Evaporative Emission Control System Vent Control Circuit Open",
        ["P0448"] = "Evaporative Emission Control System Vent Control Circuit Shorted",
        ["P0449"] = "Evaporative Emission Control System Vent Valve/Solenoid Circuit Malfunction",
        ["P0450"] = "Evaporative Emission Control System Pressure Sensor Malfunction",
        ["P0451"] = "Evaporative Emission Control System Pressure Sensor Range/Performance",
        ["P0452"] = "Evaporative Emission Control System Pressure Sensor Low Input",
        ["P0453"] = "Evaporative Emission Control System Pressure Sensor High Input",
        ["P0454"] = "Evaporative Emission Control System Pressure Sensor Intermittent",
        ["P0455"] = "Evaporative Emission Control System Leak Detected (Gross Leak)",
        ["P0456"] = "Evaporative Emission Control System Leak Detected (Very Small Leak)",
        ["P0457"] = "Evaporative Emission Control System Leak Detected (Fuel Cap Loose/Off)",
        ["P0458"] = "Evaporative Emission Control System Purge Control Valve Circuit Low",
        ["P0459"] = "Evaporative Emission Control System Purge Control Valve Circuit High",
        ["P0460"] = "Fuel Level Sensor Circuit Malfunction",
        ["P0461"] = "Fuel Level Sensor Circuit Range/Performance",
        ["P0462"] = "Fuel Level Sensor Circuit Low Input",
        ["P0463"] = "Fuel Level Sensor Circuit High Input",
        ["P0464"] = "Fuel Level Sensor Circuit Intermittent",
        ["P0465"] = "Purge Flow Sensor Circuit Malfunction",
        ["P0466"] = "Purge Flow Sensor Circuit Range/Performance",
        ["P0467"] = "Purge Flow Sensor Circuit Low Input",
        ["P0468"] = "Purge Flow Sensor Circuit High Input",
        ["P0469"] = "Purge Flow Sensor Circuit Intermittent",
        ["P0470"] = "Exhaust Pressure Sensor Malfunction",
        ["P0471"] = "Exhaust Pressure Sensor Range/Performance",
        ["P0472"] = "Exhaust Pressure Sensor Low",
        ["P0473"] = "Exhaust Pressure Sensor High",
        ["P0474"] = "Exhaust Pressure Sensor Intermittent",
        ["P0475"] = "Exhaust Pressure Control Valve Malfunction",
        ["P0476"] = "Exhaust Pressure Control Valve Range/Performance",
        ["P0477"] = "Exhaust Pressure Control Valve Low",
        ["P0478"] = "Exhaust Pressure Control Valve High",
        ["P0479"] = "Exhaust Pressure Control Valve Intermittent",
        ["P0480"] = "Cooling Fan 1 Control Circuit Malfunction",
        ["P0481"] = "Cooling Fan 2 Control Circuit Malfunction",
        ["P0482"] = "Cooling Fan 3 Control Circuit Malfunction",
        ["P0483"] = "Cooling Fan Rationality Check Malfunction",
        ["P0484"] = "Cooling Fan Circuit Over Current",
        ["P0485"] = "Cooling Fan Power/Ground Circuit Malfunction",

        ["P0500"] = "Vehicle Speed Sensor Malfunction",
        ["P0501"] = "Vehicle Speed Sensor Range/Performance",
        ["P0502"] = "Vehicle Speed Sensor Circuit Low Input",
        ["P0503"] = "Vehicle Speed Sensor Intermittent/Erratic/High",
        ["P0504"] = "Brake Switch A/B Correlation",
        ["P0505"] = "Idle Control System Malfunction",
        ["P0506"] = "Idle Control System RPM Lower Than Expected",
        ["P0507"] = "Idle Control System RPM Higher Than Expected", 
        ["P0508"] = "Cold Start Idle Air Control System Malfunction",
        ["P0509"] = "Cold Start Idle Air Control System Malfunction",
        ["P0510"] = "Closed Throttle Position Switch Malfunction",
        ["P0520"] = "Engine Oil Pressure Sensor/Switch Circuit Malfunction",
        ["P0521"] = "Engine Oil Pressure Sensor/Switch Range/Performance",
        ["P0522"] = "Engine Oil Pressure Sensor/Switch Low Voltage",
        ["P0523"] = "Engine Oil Pressure Sensor/Switch High Voltage",
        ["P0524"] = "Engine Oil Pressure Too Low",
        ["P0525"] = "Cruise Control Servo Control Circuit Range/Performance",
        ["P0526"] = "Cooling Fan Speed Sensor Circuit Malfunction",
        ["P0527"] = "Cooling Fan Speed Sensor Circuit Range/Performance",
        ["P0528"] = "Cooling Fan Speed Sensor Circuit No Signal",
        ["P0529"] = "Cooling Fan Speed Sensor Circuit Intermittent",
        ["P0530"] = "A/C Refrigerant Pressure Sensor Circuit Malfunction",
        ["P0531"] = "A/C Refrigerant Pressure Sensor Circuit Range/Performance",
        ["P0532"] = "A/C Refrigerant Pressure Sensor Circuit Low Input",
        ["P0533"] = "A/C Refrigerant Pressure Sensor Circuit High Input",
        ["P0534"] = "A/C Refrigerant Charge Loss",
        ["P0550"] = "Power Steering Pressure Sensor Circuit Malfunction",
        ["P0551"] = "Power Steering Pressure Sensor Circuit Range/Performance",
        ["P0552"] = "Power Steering Pressure Sensor Circuit Low Input",
        ["P0553"] = "Power Steering Pressure Sensor Circuit High Input",
        ["P0554"] = "Power Steering Pressure Sensor Circuit Intermittent",
        ["P0560"] = "System Voltage Malfunction",
        ["P0561"] = "System Voltage Unstable",
        ["P0562"] = "System Voltage Low",
        ["P0563"] = "System Voltage High",
        ["P0565"] = "Cruise Control On Signal Malfunction",
        ["P0566"] = "Cruise Control Off Signal Malfunction",
        ["P0567"] = "Cruise Control Resume Signal Malfunction",
        ["P0568"] = "Cruise Control Set Signal Malfunction",
        ["P0569"] = "Cruise Control Coast Signal Malfunction",
        ["P0570"] = "Cruise Control Accel Signal Malfunction",

        ["P0700"] = "Transmission Control System Malfunction",
        ["P0701"] = "Transmission Control System Range/Performance",
        ["P0702"] = "Transmission Control System Electrical",
        ["P0703"] = "Torque Converter/Brake Switch B Circuit Malfunction",
        ["P0704"] = "Clutch Switch Input Circuit Malfunction",
        ["P0705"] = "Transmission Range Sensor Circuit Malfunction (PRNDL Input)",
        ["P0706"] = "Transmission Range Sensor Circuit Range/Performance",
        ["P0707"] = "Transmission Range Sensor Circuit Low Input",
        ["P0708"] = "Transmission Range Sensor Circuit High Input",
        ["P0709"] = "Transmission Range Sensor Circuit Intermittent",
        ["P0710"] = "Transmission Fluid Temperature Sensor Circuit Malfunction",
        ["P0711"] = "Transmission Fluid Temperature Sensor Circuit Range/Performance",
        ["P0712"] = "Transmission Fluid Temperature Sensor Circuit Low Input",
        ["P0713"] = "Transmission Fluid Temperature Sensor Circuit High Input",
        ["P0714"] = "Transmission Fluid Temperature Sensor Circuit Intermittent",
        ["P0715"] = "Input/Turbine Speed Sensor Circuit Malfunction",
        ["P0716"] = "Input/Turbine Speed Sensor Circuit Range/Performance",
        ["P0717"] = "Input/Turbine Speed Sensor Circuit No Signal",
        ["P0718"] = "Input/Turbine Speed Sensor Circuit Intermittent",
        ["P0719"] = "Torque Converter/Brake Switch B Circuit Low",
        ["P0720"] = "Output Speed Sensor Circuit Malfunction",
        ["P0721"] = "Output Speed Sensor Circuit Range/Performance",
        ["P0722"] = "Output Speed Sensor Circuit No Signal",
        ["P0723"] = "Output Speed Sensor Circuit Intermittent",
        ["P0724"] = "Torque Converter/Brake Switch B Circuit High",
        ["P0725"] = "Engine Speed Input Circuit Malfunction",
        ["P0726"] = "Engine Speed Input Circuit Range/Performance",
        ["P0727"] = "Engine Speed Input Circuit No Signal",
        ["P0728"] = "Engine Speed Input Circuit Intermittent",
        ["P0729"] = "Gear 6 Incorrect Ratio",
        ["P0730"] = "Incorrect Gear Ratio",
        ["P0731"] = "Gear 1 Incorrect Ratio",
        ["P0732"] = "Gear 2 Incorrect Ratio",
        ["P0733"] = "Gear 3 Incorrect Ratio",
        ["P0734"] = "Gear 4 Incorrect Ratio",
        ["P0735"] = "Gear 5 Incorrect Ratio",
        ["P0736"] = "Reverse Incorrect Ratio",
        ["P0740"] = "Torque Converter Clutch Circuit Malfunction",
        ["P0741"] = "Torque Converter Clutch Circuit Performance or Stuck Off",
        ["P0742"] = "Torque Converter Clutch Circuit Stuck On",
        ["P0743"] = "Torque Converter Clutch Circuit Electrical",
        ["P0744"] = "Torque Converter Clutch Circuit Intermittent",
        ["P0745"] = "Pressure Control Solenoid Malfunction",
        ["P0746"] = "Pressure Control Solenoid Performance or Stuck Off",
        ["P0747"] = "Pressure Control Solenoid Stuck On",
        ["P0748"] = "Pressure Control Solenoid Electrical",
        ["P0749"] = "Pressure Control Solenoid Intermittent",
        ["P0750"] = "Shift Solenoid A Malfunction",
        ["P0751"] = "Shift Solenoid A Performance or Stuck Off",
        ["P0752"] = "Shift Solenoid A Stuck On",
        ["P0753"] = "Shift Solenoid A Electrical",
        ["P0754"] = "Shift Solenoid A Intermittent",
        ["P0755"] = "Shift Solenoid B Malfunction",
        ["P0756"] = "Shift Solenoid B Performance or Stuck Off",
        ["P0757"] = "Shift Solenoid B Stuck On",
        ["P0758"] = "Shift Solenoid B Electrical",
        ["P0759"] = "Shift Solenoid B Intermittent",
        ["P0760"] = "Shift Solenoid C Malfunction",
        ["P0761"] = "Shift Solenoid C Performance or Stuck Off",
        ["P0762"] = "Shift Solenoid C Stuck On",
        ["P0763"] = "Shift Solenoid C Electrical",
        ["P0764"] = "Shift Solenoid C Intermittent",
        ["P0765"] = "Shift Solenoid D Malfunction",
        ["P0766"] = "Shift Solenoid D Performance or Stuck Off",
        ["P0767"] = "Shift Solenoid D Stuck On",
        ["P0768"] = "Shift Solenoid D Electrical",
        ["P0769"] = "Shift Solenoid D Intermittent",
        ["P0770"] = "Shift Solenoid E Malfunction",
        ["P0771"] = "Shift Solenoid E Performance or Stuck Off",
        ["P0772"] = "Shift Solenoid E Stuck On",
        ["P0773"] = "Shift Solenoid E Electrical",
        ["P0774"] = "Shift Solenoid E Intermittent",

        ["C0035"] = "Left Front Wheel Speed Circuit Malfunction",
        ["C0040"] = "Right Front Wheel Speed Circuit Malfunction", 
        ["C0045"] = "Left Rear Wheel Speed Circuit Malfunction",
        ["C0050"] = "Right Rear Wheel Speed Circuit Malfunction",
        ["C0060"] = "ABS Solenoid Circuit Malfunction",
        ["C0121"] = "Valve Relay Circuit Malfunction",
        ["C0140"] = "ABS System Internal Malfunction",

        ["B0001"] = "Driver Airbag Circuit Resistance High",
        ["B0002"] = "Driver Airbag Circuit Resistance Low",
        ["B0003"] = "Driver Airbag Circuit Short to Ground",
        ["B0004"] = "Driver Airbag Circuit Short to Battery",
        ["B0005"] = "Passenger Airbag Circuit Resistance High",
        ["B0006"] = "Passenger Airbag Circuit Resistance Low",
        ["B0010"] = "Driver Side Impact Sensor Circuit Resistance High",
        ["B0015"] = "Passenger Side Impact Sensor Circuit Resistance High",
        
        ["U0001"] = "High Speed CAN Communication Bus",
        ["U0002"] = "High Speed CAN Communication Bus Performance",
        ["U0003"] = "High Speed CAN Communication Bus (+) Open",
        ["U0004"] = "High Speed CAN Communication Bus (+) Low",
        ["U0005"] = "High Speed CAN Communication Bus (+) High",
        ["U0006"] = "High Speed CAN Communication Bus (-) Open",
        ["U0007"] = "High Speed CAN Communication Bus (-) Low", 
        ["U0008"] = "High Speed CAN Communication Bus (-) High",
        ["U0100"] = "Lost Communication with ECM/PCM",
        ["U0101"] = "Lost Communication with TCM",
        ["U0102"] = "Lost Communication with Transfer Case Control Module",
        ["U0103"] = "Lost Communication with Gear Shift Module",
        ["U0104"] = "Lost Communication with Cruise Control Module",
        ["U0105"] = "Lost Communication with Fuel Injector Control Module",
        ["U0106"] = "Lost Communication with Glow Plug Control Module",
        ["U0107"] = "Lost Communication with Throttle Actuator Control Module",
        ["U0108"] = "Lost Communication with Alternative Fuel Control Module",
        ["U0109"] = "Lost Communication with Fuel Pump Control Module",
        ["U0110"] = "Lost Communication with Drive Motor Control Module",
        ["U0111"] = "Lost Communication with Battery Energy Control Module",
        ["U0112"] = "Lost Communication with Battery Pack Control Module",
        ["U0113"] = "Lost Communication with Emissions Critical Control Module",
        ["U0114"] = "Lost Communication with Four Wheel Drive Control Module",
        ["U0115"] = "Lost Communication with Engine Control Module",
        ["U0121"] = "Lost Communication with Anti-Lock Brake System Control Module",
        ["U0122"] = "Lost Communication with Vehicle Dynamics Control Module",
        ["U0123"] = "Lost Communication with Electric Brake Control Module",
        ["U0124"] = "Lost Communication with Hybrid Powertrain Control Module",
        ["U0125"] = "Lost Communication with Multi-Axis Acceleration Sensor Module",
        ["U0126"] = "Lost Communication with Steering Angle Sensor Module",
        ["U0127"] = "Lost Communication with Tire Pressure Monitor Module",
        ["U0128"] = "Lost Communication with Park Brake Control Module",
        ["U0129"] = "Lost Communication with Brake System Control Module",
        ["U0140"] = "Lost Communication with Body Control Module",
        ["U0141"] = "Lost Communication with Body Control Module A",
        ["U0142"] = "Lost Communication with Body Control Module B",
        ["U0143"] = "Lost Communication with Body Control Module C",
        ["U0144"] = "Lost Communication with Body Control Module D",
        ["U0145"] = "Lost Communication with Gateway Module A",
        ["U0146"] = "Lost Communication with Gateway Module B",
        ["U0147"] = "Lost Communication with Gateway Module C",
        ["U0148"] = "Lost Communication with Gateway Module D",
        ["U0149"] = "Lost Communication with Electronic Brake and Traction Control Module",
        ["U0151"] = "Lost Communication with Restraints Control Module",
        ["U0152"] = "Lost Communication with Side Restraints Control Module",
        ["U0153"] = "Lost Communication with Restraints Control Module B",
        ["U0154"] = "Lost Communication with Restraints Control Module C",
        ["U0155"] = "Lost Communication with Instrument Panel Control Module",
        ["U0156"] = "Lost Communication with Information and Radio Display Module",
        ["U0157"] = "Lost Communication with Data Link Connector Module",
        ["U0158"] = "Lost Communication with Transceivers/GPS Navigation Module",
        ["U0159"] = "Lost Communication with Parking Assistance Control Module",
        ["U0160"] = "Lost Communication with Audible Warning and Chime Module",
        ["U0161"] = "Lost Communication with Radio Frequency Receiver",
        ["U0162"] = "Lost Communication with Digital Disc Player Control Module",
        ["U0163"] = "Lost Communication with Navigation Display Module",
        ["U0164"] = "Lost Communication with HVAC Control Module",
        ["U0165"] = "Lost Communication with Instrument Panel Dimming Control Module",
        ["U0166"] = "Lost Communication with Seat Control Module",
        ["U0167"] = "Lost Communication with Immobilizer Control Module",
        ["U0168"] = "Lost Communication with Vehicle Theft Deterrent Control Module",
        ["U0169"] = "Lost Communication with Sunroof Control Module",
        ["U0170"] = "Lost Communication with Antenna Control Module",
        ["U0171"] = "Lost Communication with Satellite Radio Module",
        ["U0172"] = "Lost Communication with Digital Audio Control Module A",
        ["U0173"] = "Lost Communication with Digital Audio Control Module B",
        ["U0174"] = "Lost Communication with Telematics Control Module",
        ["U0175"] = "Lost Communication with Delivery Vehicle Operations Center",
        ["U0176"] = "Lost Communication with Personalization Module",
        ["U0177"] = "Lost Communication with Entertainment Control Module",
        ["U0178"] = "Lost Communication with Electronic Automatic Temperature Control Module",
        ["U0179"] = "Lost Communication with Electronic Heated Steering Wheel Module",
        ["U0180"] = "Lost Communication with Remote Function Actuator A",
        ["U0181"] = "Lost Communication with Compass Module",
        ["U0182"] = "Lost Communication with Magnetic Ride Control Module",
        ["U0183"] = "Lost Communication with Vehicle Security Control Module",
        ["U0184"] = "Lost Communication with Digital Audio Control Module C",
        ["U0185"] = "Lost Communication with Headlamp Control Module",
        ["U0186"] = "Lost Communication with Footwell Lighting Control Module",
        ["U0187"] = "Lost Communication with Electronic Suspension Control Module",
        ["U0188"] = "Lost Communication with Auto Stop Module",
        ["U0189"] = "Lost Communication with Rear Gate Control Module",
        ["U0190"] = "Lost Communication with Memory Seat Control Module",
        ["U0191"] = "Lost Communication with Occupant Sensing Module",
        ["U0192"] = "Lost Communication with Door Control Module A",
        ["U0193"] = "Lost Communication with Door Control Module B",
        ["U0194"] = "Lost Communication with Door Control Module C",
        ["U0195"] = "Lost Communication with Door Control Module D",
        ["U0196"] = "Lost Communication with Door Control Module E",
        ["U0197"] = "Lost Communication with Door Control Module F",
        ["U0198"] = "Lost Communication with Door Control Module G",
        ["U0199"] = "Lost Communication with Door Control Module H"
    }.ToFrozenDictionary();

    public string? GetDescription(string dtcCode)
    {
        if (string.IsNullOrWhiteSpace(dtcCode))
            return null;

        var code = dtcCode.Trim().ToUpperInvariant();
        
        if (DtcDescriptions.TryGetValue(code, out var description))
            return description;

        return GetGenericDescription(code);
    }

    public string GetSystemName(string systemCode)
    {
        if (string.IsNullOrWhiteSpace(systemCode))
            return "Unknown";

        var code = systemCode.Trim().ToUpperInvariant();
        return SystemNames.TryGetValue(code, out var name) ? name : "Unknown";
    }

    private static string GetGenericDescription(string dtcCode)
    {
        if (dtcCode.Length < 2)
            return "Unknown diagnostic trouble code";

        var systemCode = dtcCode[0].ToString();
        var numericPart = dtcCode[1..];

        var systemName = systemCode switch
        {
            "P" => "Powertrain",
            "C" => "Chassis", 
            "B" => "Body",
            "U" => "Network/Communication",
            _ => "Unknown System"
        };

        return $"{systemName} diagnostic trouble code {dtcCode} (description not available)";
    }
}

